### ISSUE TITLE
As a User , needs password security  to operate the system

### ISSUE THREAD

**Issue by JASPREETMINHAS** [0xskynet/comp313#11]
As a User, needs password security to operate the system.

**Comment by hlac** [comment]
The first character of a user role name is always capitalized.




Best Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by JASPREETMINHAS** [comment]
Sorry professor, I will make it correct.

**Comment by 0xskynet** [comment]
Duplicate of issue #10.
