### ISSUE TITLE
Requirements gathering

### ISSUE THREAD

**Issue by hlac** [0xskynet/comp313#2]
For each new feature, you need user stories and tasks to clearly describe the functionalities

**Comment by krushnsinh** [comment]
<img width="621" alt="screen shot 2017-02-08 at 7 58 02 pm" src="https://cloud.githubusercontent.com/assets/11771675/22764496/08e7fe2e-ee39-11e6-90c6-fdc426ceafca.png">

**Comment by aamir030** [comment]
Low fidelity prototype for new features added to project document

**Comment by aamir030** [comment]
User stories for new features added in project document

**Comment by hlac** [comment]
Each box requires a user story (written as an issue) and disaggregated tasks (written as individual issues).  Being written as an issue allows for ownership, and hence, responsibility as to who is responsible for completing it.
