### ISSUE TITLE
As a User, I want the better Graphical User Interface.

### ISSUE THREAD

**Issue by JASPREETMINHAS** [0xskynet/comp313#20]

**Comment by hlac** [comment]
This is a NFR (non-functional requirement) and cannot be implemented.  You
can test against it only if you quantify it.  Do you have a metric in
mind?  If not, close it with a comment "INVALID".


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by 0xskynet** [comment]
Invalid user story.
